import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function POST(req: NextRequest) {
  const { meeting_id, to_email } = await req.json()
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const [{ data: meeting }, { data: notes }, { data: actionItems }] = await Promise.all([
    supabase.from('cb_meetings').select('*, contact:cb_contacts(*)').eq('id', meeting_id).single(),
    supabase.from('cb_meeting_notes').select('*').eq('meeting_id', meeting_id).single(),
    supabase.from('cb_action_items').select('*').eq('meeting_id', meeting_id).order('created_at'),
  ])

  if (!meeting || !notes) return NextResponse.json({ error: 'Meeting or notes not found' }, { status: 404 })

  const contact = meeting.contact
  const meetingDate = new Date(meeting.meeting_date).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  })

  const actionItemsHtml = (actionItems ?? []).map((a, i) =>
    `<tr>
      <td style="padding:8px 12px;border:1px solid #E5E7EB;">${i + 1}. ${a.description}</td>
      <td style="padding:8px 12px;border:1px solid #E5E7EB;">${a.owner ?? '—'}</td>
      <td style="padding:8px 12px;border:1px solid #E5E7EB;">${a.due_date ?? '—'}</td>
    </tr>`
  ).join('')

  const html = `
<div style="font-family:Arial,sans-serif;max-width:680px;margin:0 auto;color:#1F2937;">
  <div style="background:#4F46E5;padding:24px 32px;border-radius:12px 12px 0 0;">
    <h1 style="color:white;margin:0;font-size:20px;">🤝 Minutes of Meeting</h1>
    <p style="color:#A5B4FC;margin:4px 0 0;font-size:14px;">${meetingDate}</p>
  </div>
  <div style="background:white;padding:32px;border:1px solid #E5E7EB;">
    <h2 style="color:#374151;font-size:16px;margin-bottom:4px;">${contact?.full_name ?? ''}</h2>
    <p style="color:#6B7280;font-size:14px;margin:0 0 24px;">${contact?.title ?? ''} · ${contact?.company ?? ''}</p>

    <h3 style="color:#4F46E5;font-size:14px;text-transform:uppercase;letter-spacing:0.05em;">Bottom-Line Summary</h3>
    <div style="background:#F9FAFB;border-radius:8px;padding:16px;margin-bottom:24px;font-size:14px;line-height:1.7;">
      ${(notes.bottom_line_summary ?? '').split('\n').map(l => `<p style="margin:0 0 4px;">${l}</p>`).join('')}
    </div>

    <h3 style="color:#4F46E5;font-size:14px;text-transform:uppercase;letter-spacing:0.05em;">Meeting Intent</h3>
    <p style="font-size:14px;color:#374151;margin-bottom:24px;">${notes.intent ?? ''}</p>

    <h3 style="color:#4F46E5;font-size:14px;text-transform:uppercase;letter-spacing:0.05em;">Action Items</h3>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;font-size:13px;">
      <thead>
        <tr style="background:#EEF2FF;">
          <th style="padding:8px 12px;border:1px solid #E5E7EB;text-align:left;">Action Item</th>
          <th style="padding:8px 12px;border:1px solid #E5E7EB;text-align:left;">Owner</th>
          <th style="padding:8px 12px;border:1px solid #E5E7EB;text-align:left;">Due Date</th>
        </tr>
      </thead>
      <tbody>${actionItemsHtml || '<tr><td colspan="3" style="padding:8px 12px;border:1px solid #E5E7EB;color:#9CA3AF;">No action items</td></tr>'}</tbody>
    </table>

    <p style="font-size:12px;color:#9CA3AF;margin-top:32px;border-top:1px solid #F3F4F6;padding-top:16px;">
      Generated by ConfBuddy · HighRadians
    </p>
  </div>
</div>`

  // For now, return the HTML — Gmail MCP integration would send this
  // In production: use Gmail MCP tool or nodemailer/SendGrid
  const recipient = to_email ?? user.email
  return NextResponse.json({
    success: true,
    message: `Email prepared for ${recipient}`,
    html_preview: html.substring(0, 200) + '...'
  })
}
